{% set name = "lupa" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lupa-{{ version }}.tar.gz
  sha256: 760030712d5273396f5e963dd8731aefb5ac65d92eff8bf8fd4124c1630fe950

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - python
    - cython
    - lua
    - luajit
  host:
    - python
    - cython
    - pip
  run:
    - python

test:
  imports:
    - lupa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scoder/lupa
  summary: Python wrapper around Lua and LuaJIT
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
