{% set name = "lupa" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lupa-{{ version }}.tar.gz
  sha256: d0fd4e60ad149fe25c90530e2a0e032a42a6f0455f29ca0edb8170d6ec751c6e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  skip: true  # [win]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python
    - cython
    - lua
    - luajit
  host:
    - python
    - cython
    - pip
  run:
    - python

test:
  imports:
    - lupa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scoder/lupa
  summary: Python wrapper around Lua and LuaJIT
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - lincrosenbach
    - mv-per
    - brnomendes
